### ISSUE TITLE
[BUG] /reload causes Enchantment Upgrades to fail, requires world restart to fix.

### ISSUE THREAD

**Issue by SuperKnux** [DaFuqs/Spectrum#460]
**Describe the bug**
If you use /reload or change datapacks, Enchantment Upgrade recipes fail, becoming unable to be viewed and used. This requires a world restart to fix.

**To Reproduce**
Enter a world.
Use /reload.
Check a non-level-1 enchantment book's recipe or check the Spectrum book's enchantment category.

**Expected behavior**
The Enchantment Upgrade's recipe should be available and useable.

**Minecraft version**
1.20.1

**Mod version**
1.7.16

**Screenshots**
![image](https://github.com/user-attachments/assets/b01e041b-9343-49a1-8453-2b1e7429182b)
This doesn't normally happen.
![image](https://github.com/user-attachments/assets/83e0d7b4-b543-4eb9-b03c-da7d3faa14f1)
These appear when a /reload occurs.

**Crash Report**
If it is a crash bug add your crash log here

**Comment by DaFuqs** [comment]
Related to https://github.com/KubeJS-Mods/KubeJS/issues/293
I guess the workaround I added for KubeJS broke somehow.

**Comment by f-raZ0R** [comment]
Seems to have been fixed on KubeJS's side
(again, do not have the perms to close this issue myself)

**Comment by Mouy07** [comment]
This is still happening on the latest version, even with no other mods installed (other than dependencies and EMI).

**Comment by unilock** [comment]
I can confirm that this still occurs on Fabric 1.20.1 + Spectrum 1.8.6 with no other mods installed, aside from Spectrum, its dependencies, and EMI.
