### ISSUE TITLE
Inexorable enchantment causes the game to crash

### ISSUE THREAD

**Issue by GRAINALCOHOL** [DaFuqs/Spectrum#680]
**Describe the Bug**
The game becomes unresponsive as soon as you enter the save and successfully load the world. I made some preliminary judgments: it could be a NullPointerException thrown by the mixin method of applyInexorableAntiSlowdown

**To Reproduce**
I don't know how to reproduce the bug because I haven't started playing it yet

**Expected behavior**
The game should not be unresponsive

**Minecraft version**
1.20.1fabric，loader0.16.10，api0.92.3

**Mod version**
1.8.0alpha3

**Crash Report**
https://mclo.gs/PzyWOQK

**Comment by Noaaan** [comment]
This crash should already be fixed in the latest version of Spectrum. I suggest updating

**Comment by GRAINALCOHOL** [comment]
I updated to the latest version (1.8.4) but the game still doesn't respond from time to time like the previous submission, I sent the crash report to the AI for analysis, it said that the bug is related to the interaction between Apugli (a dependency of origins) and Spectrum, specifically triggered in Spectrum's InexorableEnchantment class, but I don't want to remove either mod

[crash-2025-03-02_18.13.18-server.txt](https://github.com/user-attachments/files/19043143/crash-2025-03-02_18.13.18-server.txt)
